/**
 * Domain routing: a PAC script generated from a list of domains — only the sites
 * you name go through your servers, everything else stays direct. `fixed_servers`
 * cannot express that, its bypass list can only *exclude*.
 *
 * Three decisions are load-bearing: a listed domain never falls back to `DIRECT`,
 * the chain is every saved server, everything else is direct — and `bypassList`
 * keeps its meaning: those hosts never use a proxy, even when a rule matches.
 */

import { sanitizeDomainRules } from './model.js';

/**
 * PAC proxies are named by protocol: "PROXY" is an HTTP proxy, "HTTPS" one that
 * speaks TLS, "SOCKS4"/"SOCKS5" the SOCKS variants.
 */
export const PAC_DIRECTIVE = {
  http: 'PROXY',
  https: 'HTTPS',
  socks4: 'SOCKS4',
  socks5: 'SOCKS5',
};

/** The `<local>` token in a bypass list: every host without a dot. */
export const PLAIN_HOST_RULE = '<local>';

/** The rule a proxy directive is built from, e.g. `PROXY proxy.example.com:8080`. */
export function proxyDirective(profile) {
  const directive = PAC_DIRECTIVE[profile?.scheme] ?? PAC_DIRECTIVE.http;
  return `${directive} ${profile.host}:${Number(profile.port)}`;
}

/**
 * The servers the script may try, in order. `; ` is how a PAC script says "and
 * then", and Chrome walks the chain per connection.
 *
 * @param {object[]} servers
 * @returns {string} `PROXY a:8080; SOCKS5 b:1080`, or '' when there is no server
 */
export function proxyChain(servers) {
  const directives = [];
  const seen = new Set();

  for (const server of Array.isArray(servers) ? servers : []) {
    if (!server?.host) continue;
    const directive = proxyDirective(server);
    if (seen.has(directive)) continue;
    seen.add(directive);
    directives.push(directive);
  }

  return directives.join('; ');
}

/**
 * Builds the PAC script for a chain of servers and a domain list.
 *
 * @param {object} options
 * @param {object[]} options.servers the chain, in the order it is tried
 * @param {string[]} [options.domains] the hosts the chain is for (the base
 *        policy is an allow list unless `base` says otherwise)
 * @param {string[]} [options.bypass] hosts that never use a proxy
 * @param {'listed'|'all'} [options.base] what the chain is for when no other rule
 *        matches: the listed hosts, or every host (how manual mode behaves)
 * @param {{hosts?: string[], directive?: string}|null} [options.override] a
 *        directive handed to a few named hosts — how a background check sends
 *        *its own* probe to the server it is testing
 * @returns {string|null} the script, or null when there is nothing to route
 *          (no server, or no usable rule) — the caller then fails open
 */
export function buildPacScript({ servers, domains, bypass = [], base = 'listed', override = null }) {
  const chain = proxyChain(servers);
  const rules = sanitizeDomainRules(domains);
  const routeEverything = base === 'all';
  if (!chain) return null;
  if (rules.length === 0 && !routeEverything) return null;

  // An override needs both halves, or it diverts nothing while looking like it
  // does.
  const overrideHosts = (Array.isArray(override?.hosts) ? override.hosts : [])
    .map((host) => String(host ?? '').trim().toLowerCase())
    .filter(Boolean);
  const overrideDirective = String(override?.directive ?? '').trim();
  const overrides = overrideHosts.length > 0 && overrideDirective !== '';

  const names = (Array.isArray(servers) ? servers : [])
    .filter((server) => server?.host)
    .map((server) => server.name);
  const bypassRules = sanitizeDomainRules(bypass);

  const policy = routeEverything
    ? '// Every host uses the proxy chain; the bypass list still wins.'
    : '// The rules below are an allow list: only those hosts use the proxy chain.\n// A matched host is never sent direct, even when every server is unreachable\n// (a leak would defeat the point of listing it).';

  return `// Generated by Proxy Switch — ${rules.length} domain rule(s) through ${JSON.stringify(names)}.
${policy}${overrides ? '\n// A few hosts below go to one named server: the extension probing it.' : ''}
var PROXIES = ${JSON.stringify(chain)};
var ROUTED = ${JSON.stringify(rules)};
var BYPASSED = ${JSON.stringify(bypassRules)};
var ALL_HOSTS = ${routeEverything ? 'true' : 'false'};
var OVERRIDE = ${JSON.stringify(overrides ? overrideDirective : '')};
var OVERRIDE_HOSTS = ${JSON.stringify(overrides ? overrideHosts : [])};

// One rule against one host. A plain name covers the domain and its subdomains,
// "*.example.com" only the subdomains, "<local>" every dot-less host, and any
// other "*"/"?" is a glob (the PAC-standard shExpMatch).
function hostMatches(host, rule) {
  var value = String(host).toLowerCase().replace(/^\\[|\\]$/g, '');
  var pattern = String(rule).toLowerCase().replace(/^\\[|\\]$/g, '');
  if (pattern === ${JSON.stringify(PLAIN_HOST_RULE)}) return isPlainHostName(value);
  if (pattern.slice(0, 2) === '*.') {
    var bare = pattern.slice(2);
    return value.length > bare.length && value.slice(-(bare.length + 1)) === '.' + bare;
  }
  if (pattern.indexOf('*') !== -1 || pattern.indexOf('?') !== -1) return shExpMatch(value, pattern);
  return value === pattern || value.slice(-(pattern.length + 1)) === '.' + pattern;
}

function anyMatch(host, rules) {
  for (var index = 0; index < rules.length; index += 1) {
    if (hostMatches(host, rules[index])) return true;
  }
  return false;
}

// Exact host, no subdomains: the extension's own probe endpoints.
function isOverrideHost(host) {
  var value = String(host).toLowerCase().replace(/^\\[|\\]$/g, '').split(':')[0];
  for (var index = 0; index < OVERRIDE_HOSTS.length; index += 1) {
    if (OVERRIDE_HOSTS[index] === value) return true;
  }
  return false;
}

function FindProxyForURL(url, host) {
  // A probe goes where the check asked for, bypass list or not.
  if (OVERRIDE !== '' && isOverrideHost(host)) return OVERRIDE;
  // Bypass list: these hosts never see a proxy.
  if (anyMatch(host, BYPASSED)) return 'DIRECT';
  // The chain: the next server is tried when the first one fails.
  if (ALL_HOSTS || anyMatch(host, ROUTED)) return PROXIES;
  return 'DIRECT';
}
`;
}
